# USA Economy Analysis:

## 01-data-audit: What do we have?

## Project Overview

In this project, three raw datasets — GDP, CPI, and Unemployment — were obtained from Kaggle. The objective is to analyze these economic indicators and gain insights into the U.S. economy over the period from 1974 to 2024.

## Imports

In [45]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

## Loading Data

In [46]:
DATA_PATH =Path("../data/raw")

In [47]:
df_gdp = pd.read_csv(DATA_PATH / "gdp_data.csv")

In [48]:
df_cpi = pd.read_csv(DATA_PATH / "cpi_data.csv")

In [49]:
df_unemployment = pd.read_csv(DATA_PATH / "unemployment_data.csv")

## Data Observation

In [50]:
df_gdp.head()

         DATE       GDP
0  1974-01-01  1491.209
1  1974-04-01  1530.056
2  1974-07-01  1560.026
3  1974-10-01  1599.679
4  1975-01-01  1616.116

In [51]:
df_gdp.tail()

           DATE        GDP
196  2023-01-01  26813.601
197  2023-04-01  27063.012
198  2023-07-01  27610.128
199  2023-10-01  27956.998
200  2024-01-01  28269.174

In [52]:
df_cpi.head()

         DATE  CPIAUCSL
0  1974-01-01      46.8
1  1974-02-01      47.3
2  1974-03-01      47.8
3  1974-04-01      48.1
4  1974-05-01      48.6

In [53]:
df_cpi.tail()

           DATE  CPIAUCSL
596  2023-09-01   307.288
597  2023-10-01   307.531
598  2023-11-01   308.024
599  2023-12-01   308.742
600  2024-01-01   309.685

In [54]:
df_unemployment.head()

         DATE  UNRATE
0  1974-01-01     5.1
1  1974-02-01     5.2
2  1974-03-01     5.1
3  1974-04-01     5.1
4  1974-05-01     5.1

In [55]:
df_unemployment.tail()

           DATE  UNRATE
596  2023-09-01     3.8
597  2023-10-01     3.8
598  2023-11-01     3.7
599  2023-12-01     3.7
600  2024-01-01     3.7

## Dataset Shape

In [56]:
df_gdp.shape

(201, 2)

In [57]:
df_cpi.shape

(601, 2)

In [58]:
df_unemployment.shape

(601, 2)

## Missing Values

In [59]:
df_gdp.isnull().sum()

DATE    0
GDP     0
dtype: int64

In [60]:
df_cpi.isnull().sum()

DATE        0
CPIAUCSL    0
dtype: int64

In [61]:
df_unemployment.isnull().sum()

DATE      0
UNRATE    0
dtype: int64

## Duplicate Records

In [62]:
df_gdp.duplicated().sum()

np.int64(0)

In [63]:
df_cpi.duplicated().sum()

np.int64(0)

In [64]:
df_unemployment.duplicated().sum()

np.int64(0)

## Columns

In [65]:
df_gdp.columns

Index(['DATE', 'GDP'], dtype='str')

In [66]:
df_cpi.columns

Index(['DATE', 'CPIAUCSL'], dtype='str')

In [67]:
df_unemployment.columns

Index(['DATE', 'UNRATE'], dtype='str')

## Data Types

In [68]:
df_cpi.dtypes

DATE            str
CPIAUCSL    float64
dtype: object

In [69]:
df_gdp.dtypes

DATE        str
GDP     float64
dtype: object

In [70]:
df_unemployment.dtypes

DATE          str
UNRATE    float64
dtype: object


## Dataset Information

In [71]:
df_gdp.info()

<class 'pandas.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   DATE    201 non-null    str
 1   GDP     201 non-null    float64
dtypes: float64(1), str(1)
memory usage: 5.2 KB

In [72]:
df_cpi.info()

<class 'pandas.DataFrame'>
RangeIndex: 601 entries, 0 to 600
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   DATE      601 non-null    str
 1   CPIAUCSL  601 non-null    float64
dtypes: float64(1), str(1)
memory usage: 15.4 KB

In [73]:
df_unemployment.info()

<class 'pandas.DataFrame'>
RangeIndex: 601 entries, 0 to 600
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   DATE    601 non-null    str
 1   UNRATE  601 non-null    float64
dtypes: float64(1), str(1)
memory usage: 15.4 KB

## Descriptive Statistics

In [74]:
df_gdp.describe()

                GDP
count    201.000000
mean   10767.185687
std     7074.040546
min     1491.209000
25%     4607.669000
50%     9411.682000
75%    15647.680000
max    28269.174000

In [75]:
df_cpi.describe()

         CPIAUCSL
count  601.000000
mean   167.007037
std     67.734123
min     46.800000
25%    109.700000
50%    164.700000
75%    225.395000
max    309.685000

In [76]:
df_unemployment.describe()

           UNRATE
count  601.000000
mean     6.185025
std      1.751668
min      3.400000
25%      4.900000
50%      5.900000
75%      7.300000
max     14.800000

## Date Range

In [77]:
df_gdp["DATE"].min()

'1974-01-01'

In [78]:
df_gdp["DATE"].max()

'2024-01-01'

In [79]:
df_cpi["DATE"].min()

'1974-01-01'

In [80]:
df_cpi["DATE"].max()

'2024-01-01'

In [81]:
df_unemployment["DATE"].min()

'1974-01-01'

In [82]:
df_unemployment["DATE"].max()

'2024-01-01'

## Initial Data Quality Findings

- No missing values were found in the datasets.
- No duplicate records were detected.
- The datasets cover the period from 1974-01-01 to 2024-01-01.
- The data types are generally appropriate; however, the `DATE` columns can be converted to datetime format for more effective time-series analysis.
- Based on the descriptive statistics, the observed values appear to be economically reasonable. For example, unemployment rates do not contain negative values.
- CPI and unemployment data are recorded at a monthly frequency, while GDP data is recorded at a quarterly frequency. This frequency mismatch will need to be addressed during the data preparation stage.

## Audit Summary

The initial data audit is complete.

The structure, data types, missing values, duplicate records, date ranges, and basic statistical properties of the three datasets have been reviewed.

The main issue identified is the difference in data frequency between the datasets, which will be addressed in the data preparation stage.